"""remove_nnull_from_employee

Revision ID: b5b0a30ed23b
Revises: c843895e2477
Create Date: 2025-01-16 20:32:36.935764

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b5b0a30ed23b"
down_revision: Union[str, None] = "c843895e2477"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "company_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "company_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
