"""init

Revision ID: d551e0ef2026
Revises:
Create Date: 2025-01-13 18:44:57.024505

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d551e0ef2026"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("hpass", sa.String(length=60), nullable=False),
        sa.Column(
            "registration_data",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "access_level",
            sa.Enum("USER", "ADMIN", "SERVICE", name="portalaccess"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="users_email_UK"),
        sa.UniqueConstraint("login", name="users_login_UK"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
